%% Generated by the Erlang ASN.1 compiler version:4.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module Ecdsa



-ifndef(_ECDSA_HRL_).
-define(_ECDSA_HRL_, true).

-record('Sig',{
r, s}).

-endif. %% _ECDSA_HRL_
